import './bootstrap';
import '../css/admin.css';
import './admin/dashboard';
import './draftpaten/upload';
import './nextbutton';
import './hakcipta/lainnya';
import './menu';
import './alert';
import './hakpaten/isiform'
